### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by JasonMorgan** [kubernetes/kubernetes.github.io#5138] opened 2017-08-21 17:44 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The instructions tell you to run kubectl proxy, which locks the terminal. It then tells you to run another command. 

**Proposed Solution:**
Add in the instructions that the person running the tutorial should open a new terminal with some instructions.

**Page to Update:**
http://kubernetes.io/...

**Comment by radhikapc** [comment] 2017-08-21 17:45
@BenHall Hi !

**Comment by BenHall** [comment] 2017-08-22 08:19
Thank you for the feedback. This is by design on how kubectl proxy works. All the future commands launch in a separate terminal window while Kubectl Proxy is running.

We should make this clearer in the scenario text itself.

**Comment by heckj** [comment] 2017-09-12 21:34
related (original) issue: #1561

**Comment by heckj** [comment] 2017-09-13 19:35
Thanks Jason,

This bug matches closely other bugs reported against the use of `kubectl proxy` in the tutorial's hosted at Katacoda. I have a PR pending to resolve, and am closing this bug to focus conversation on the earliest report of this issue: https://github.com/kubernetes/kubernetes.github.io/issues/1561

Please comment at https://github.com/kubernetes/kubernetes.github.io/issues/1561, or subscribe to that bug, to get updates as we work on resolving this.

**Closed by heckj** 2017-09-13 19:35 UTC
Labels: P2, team/katacoda
