### ISSUE TITLE
Incorrect titles of docs 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes.github.io#1959] opened 2016-12-14 23:17 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Somehow the titles of docs are incorrect, they should be read from _data/xxx.yml, but it now becomes the first heading `###` in the md file, e.g. http://kubernetes.io/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set/ @kubernetes/sig-docs @devin-donnelly @steveperry-53

**Comment by steveperry-53** [comment] 2016-12-14 23:41
This is being addressed in https://github.com/kubernetes/kubernetes.github.io/pull/1942.

**Comment by janetkuo** [comment] 2016-12-15 02:40
#1942 is merged, but the issue doesn't go away http://kubernetes.io/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set/

**Comment by jessfraz** [comment] 2016-12-15 19:35
can we just switch the DNS to point to netlify so we can not have these issues anymore?

**Comment by benbalter** [comment] 2016-12-15 19:42
The problem is that the title are stored in data files (the tables of contents), and then merged into the document via an include at build time, which is a non-standard implementation (which I haven't seen before). Because the documents themselves don't have a title, Jekyll's trying to be helpful and guess the title from the first heading, which is incorrect.

I'm about half way through a fix in the other window (to move the title to the documents themselves), which should prevent these headaches going forward, and I hope to have be able to open the PR later this afternoon.

**Comment by jessfraz** [comment] 2016-12-15 19:47
ah I found the `seo title=false`, but i also have no idea what I am doing lol

**Comment by jessfraz** [comment] 2016-12-15 19:48
I can move all the titles if that's the fix you dont need to do that!

**Closed** 2017-02-11 02:40 UTC
Labels: kind/bug
