### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by keuller** [kubernetes/kubernetes.github.io#2101] opened 2017-01-02 15:08 UTC
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
We can't click START button and start the module

**Proposed Solution:**
Corret advertise on footer page.

**Page to Update:**
http://kubernetes.io/...

**Comment by a-mccarthy** [comment] 2017-01-10 21:34
duplicate of #2037 and #2050. closing this issue. Please follow issue under #2050

**Closed by a-mccarthy** 2017-01-10 21:34 UTC
