### ISSUE TITLE
problems with kubectl_get page: horizontal slider broken, and some escaping broken

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes.github.io#76] opened 2016-03-08 20:20 UTC
http://kubernetes.github.io/docs/user-guide/kubectl/kubectl_get/

the horizontal slider in the "options" section actually doesn't slide, and it looks like the template isn't escaped properly in the line
`kubectl get -o template pod/web-pod-13je7 --template= --api-version=v1` (the --template argument shouldn't be empty)

**Comment by CreaturesInUnitards** [comment] 2016-03-08 20:25
David, are you saying you can't get the "options" code section to scroll? If so, I don't repro that — what's your browser?

**Comment by davidopp** [comment] 2016-03-08 20:38
Correct. I'm using Chrome 48.0.2564.116 on Linux.

**Comment by CreaturesInUnitards** [comment] 2016-03-08 21:06
Hm. No repro on Mac Chrome, Safari or Firefox, or Win IE or Chrome. 

Chrome just updated to 49.0.2623.75; maybe that takes care of it...?

**Comment by johndmulhausen** [comment] 2016-03-09 11:40
@eparis I've added {% raw %} and {% endraw %} to the examples here; perhaps the auto doc generator should do that for all captured "man" output?

**Comment by johndmulhausen** [comment] 2016-03-09 12:32
No repro on the horizontal scrollbars not working, sorry. We'll see if Eric knows of an easy way to get {% raw %} tags in on the auto-gen markdown files and then we'll be closing this.

**Comment by eparis** [comment] 2016-03-09 13:09
I can confirm the 'can't scroll the options block' using chrome 50 on linux. So at least 2 of us have that problem.

As to {% raw %} it's not a tag I know...  Is that something we need inside every \`\`\` code block? Why is this one special? I thought the whole point of \`\`\` was to make it not interpret things....

**Comment by johndmulhausen** [comment] 2016-03-09 16:06
cc @CreaturesInUnitards -- can you test on Chrome Linux? 

@eparis - Re: {% raw%}: The ``` blocks work for everything except Tags that use the [Liquid Tag Syntax](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers). So, `{{foo}}` and `{%bar%}`. That's what's happening on http://kubernetes.github.io/docs/user-guide/kubectl/kubectl_get/

**Comment by CreaturesInUnitards** [comment] 2016-03-09 16:54
investigating...

**Comment by eparis** [comment] 2016-03-09 17:06
I'm going to open a new issue about the escaping....

**Comment by eparis** [comment] 2016-03-09 17:10
I openned https://github.com/kubernetes/kubernetes.github.io/issues/81 to point out the places my quick grep saw {{ in \`\`\` block problems and to discuss `kubectl get`

**Comment by CreaturesInUnitards** [comment] 2016-03-09 17:39
@johndmulhausen: this is a problem for Linux Firefox as well. It's the pseudo-elements on H# tags, as it turns out — no amount of z-indexing will get them to go behind the elements that come before them in the DOM. I have a script which will fix this, but there's not a lot of time before launch. Recommend punting to post-launch

**Comment by johndmulhausen** [comment] 2016-03-18 00:23
Assigning to @CreaturesInUnitards to fix the scrolling. That's the only thing this bug is about now.

**Comment by CreaturesInUnitards** [comment] 2016-03-30 17:04
ok fixed

**Closed by CreaturesInUnitards** 2016-03-30 17:04 UTC
