### ISSUE TITLE
having issues when running kubectl edit deployment hello-node. I get the following response: error: there was a problem with the editor "vi"

### ISSUE THREAD

**Issue by dzuluaga** [kubernetes/kubernetes.github.io#674] opened 2016-06-16 06:56 UTC
I wish /docs/hellonode/ I'm having issues when running kubectl edit deployment hello-node. I get the following response: error: there was a problem with the editor "vi". Any idea what could be wrong? Thanks!

**Comment by runseb** [comment] 2016-06-29 12:12
Hi @dzuluaga , I assume that you manage to create the deployment properly with `kubectl` ?

If yes, what is our $EDITOR variable. Could be that it is not set properly.
Does vi works normally otherwise.

I just tested this and it works just fine.

**Comment by pselle** [comment] 2016-08-30 14:17
I've gotten the same error, `vi` works normally otherwise. `vi` is the value of `$EDITOR` in this case

**Comment by pselle** [comment] 2016-08-30 14:18
BTW, changing $EDITOR to nano works; not sure what the issue is with vi+kubernetes

**Comment by jaredbhatti** [comment] 2017-01-11 00:24
Haven't seen any movement on this issue for 6 months. Closing out.

**Closed by jaredbhatti** 2017-01-11 00:24 UTC

**Comment by alunarbeach** [comment] 2017-08-01 14:32
Setting KUBE_EDITOR="vim" explicitly helped me resolving this issue.

**Comment by yehaifeng** [comment] 2019-04-23 01:29
I got the same problem. 
Because the system don't the 'vi', only have a alias for "alias vi='vim'" but does not work. And install the vi to fix.

**Comment by soheilade** [comment] 2019-08-25 17:36
> KUBE_EDITOR="vim"

how to set KUBE_EDITOR="vim"?

**Comment by ksripathi** [comment] 2019-09-23 10:35
@soheilade 

> echo 'KUBE_EDITOR="vim"' >> ~/.bash_profile
> source ~/.bash_profile

**Comment by mikehuston** [comment] 2020-03-24 01:01
> Setting KUBE_EDITOR="vim" explicitly helped me resolving this issue.

This helped me also, thanks! Perhaps because `vi` is a symlink for `vim` on my Mac laptop.
```
ls -al /usr/bin/vi
lrwxr-xr-x  1 root  wheel  3 Mar 22  2019 /usr/bin/vi -> vim
```

**Comment by lewiscowleschipuk** [comment] 2022-03-01 13:01
I Just got this, which is weird as it was working before...

setting `KUBE_EDITOR=vim` worked a charm, even in 2022. Perhaps my vi is an alias of vim. In any case, likely not a kubernetes issue, but local environment config.

**Comment by bustopsy777** [comment] 2022-03-20 03:42
> I Just got this, which is weird as it was working before...
> 
> setting `KUBE_EDITOR=vim` worked a charm, even in 2022. Perhaps my vi is an alias of vim. In any case, likely not a kubernetes issue, but local environment config.

Hello,
Please can you help me in detail with how you did it, step by step? I am having a problem with this. Thanks

**Comment by EricoCartmanez** [comment] 2022-10-10 17:51
`export EDITOR=vim` worked for me.
