### ISSUE TITLE
I wish /docs/user-guide/overview/ http://kubernetes.io/docs/user-guide/overview/

### ISSUE THREAD

**Issue by petersq** [kubernetes/kubernetes.github.io#373] opened 2016-04-13 12:12 UTC
I wish /docs/user-guide/overview/ http://kubernetes.io/docs/user-guide/overview/

**Comment by johndmulhausen** [comment] 2016-04-15 01:09
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/328

**Closed by johndmulhausen** 2016-04-15 01:09 UTC
