### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by Crazee** [kubernetes/kubernetes.github.io#1603] opened 2016-11-01 22:42 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This page used to say how to set up a Weave network between nodes.  Now it says "See the add-ons page for a complete list of available network add-ons."  But there is no link to such a page.  I couldn't find it.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by errordeveloper** [comment] 2016-11-11 06:59
You are right, turns out link are wrong right now. The command is `kubectl apply -f https://git.io/weave-kube`, by the way. We will fix this.

**Comment by bboreham** [comment] 2016-11-11 10:30
@Crazee I tried to help here, however:

Your "Page to Update" only shows "http://kubernetes.io/..."

I guessed you meant http://kubernetes.io/docs/getting-started-guides/kubeadm/, where there is a link "See the add-ons page".  This links to http://kubernetes.io/docs/admin/addons/ which does not match your description "no link to such a page".  

All of this seems to have been in place ten days ago.

Please clarify what the problem is.

**Comment by lukemarsden** [comment] 2016-11-11 15:12
The link text is almost the same colour as the text, especially if the link has been visited before. So, perhaps we can tweak the style sheet. Or make the link bold in this case to emphasise it.

**Comment by caseydavenport** [comment] 2016-11-11 16:56
+1 for tweaking the style sheet - I find this bites me all the time (not being able to find a link).

re: the changes to the kubeadm doc, see here: https://github.com/kubernetes/kubernetes.github.io/pull/1549#discussion_r85007313

**Comment by Crazee** [comment] 2016-11-11 20:45
I did notice it a few days later when I happened to mouse-over it.  Guess you don't need to "see" it if you ever visited the page some time in the past.  If your laptop has less than ideal viewing conditions you're out of luck.  I'd make the CSS less "subtle".

**Comment by errordeveloper** [comment] 2016-11-12 03:00
@lukemarsden @caseydavenport @bboreham I've been thinking how could we optimise the UX without having a default choice and avoid taking user to other pages, so it occurred to me that we can just make HTML are bit more sophisticated  and add a drop-down menu for user to pick a network. WDYT?

**Comment by chrismarino** [comment] 2016-11-12 14:43
A drop down on a doc page seems very strange to me.  Is there any example of this anywhere? Also, makes the problem of keeping it up to date even more difficult. Not to mention possible mobile rendering and pdf probs..  A link to another page seems OK to me.

**Comment by a-mccarthy** [comment] 2017-01-12 16:00
Closing this as it seems the original issue of this issue is fixed. Please open a new issue if you'd like to discuss more ux improvements :)

**Closed by a-mccarthy** 2017-01-12 16:00 UTC
