### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by shubham023** [kubernetes/kubernetes.github.io#1792] opened 2016-11-25 07:08 UTC
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
At page http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/
console hangs at kubectl proxy step. Following happens : 
> kubectl proxy                                                                    
Starting to serve on 127.0.0.1:8001

Nothing happens and it hangs there infinitely 

**Proposed Solution:**
NA

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/ 
(Module 2 , step 3 of 3)

**Comment by chenopis** [comment] 2017-01-11 00:46
We need to move the contents of the Note to just below the "kubectl proxy" command so that it's clear to the user that they must open a new terminal tab before running the rest of the commands.

**Comment by steveperry-53** [comment] 2017-01-11 19:01
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/1561.

**Closed** 2017-01-11 19:01 UTC
Labels: Actionable, Needs Docs Review, P2

**Comment by vhosakot** [comment] 2017-02-05 23:33
I also saw this issue today and observed that `kubectl proxy` blocks and runs in the foreground and we cannot continue with the tutorial.  Hence, I used `&` and ran it in the background, and then, I was able to run all the subsequent commands successfully.

`kubectl proxy &`

Let me know if can I submit a PR to add `&` for the command `kubectl proxy` in https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/.
