### ISSUE TITLE
Broken links in reference documents from operations to definitions 

### ISSUE THREAD

**Issue by mikebrow** [kubernetes/kubernetes.github.io#323] opened 2016-04-05 18:59 UTC
In each of the api-references (e.g. `http://kubernetes.io/docs/api-reference/v1/operations/`) the links to definitions are pointing to `definitions.html` in the current directory.  However, the location of the definitions is actually in `../definitions/index.html`.

For example, ComponentStatusList is located in(at): 
`    http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_componentstatuslist`
but the link in `http://kubernetes.io/docs/api-reference/v1/operations/` is pointing to:     
`    http://kubernetes.io/docs/api-reference/v1/operations/definitions.html#_v1_componentstatuslist`

**Comment by johndmulhausen** [comment] 2016-04-15 01:10
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/341

**Closed by johndmulhausen** 2016-04-15 01:10 UTC
