### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by Uvedale** [kubernetes/kubernetes.github.io#1985] opened 2016-12-18 07:42 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
On Step 3 of Module 6, it asks the user to run:
```
kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=jocatalin/kubernetes-bootcamp:v10
```

However, this image does not exist. The version erroneously has a trailing zero.

**Proposed Solution:**
Modify the command to:
```
kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=jocatalin/kubernetes-bootcamp:v1
```

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/
(Module 6, Step 3)

**Comment by BenHall** [comment] 2017-01-10 22:31
Thanks for the feedback. This is an intentional error to simulate how Kubernetes behaves.

**Comment by a-mccarthy** [comment] 2017-01-10 23:51
@BenHall, is there anything to do for this issue? should it be closed?

**Comment by BenHall** [comment] 2017-01-10 23:53
@a-mccarthy It can be closed as it's by design.

**Closed** 2017-01-11 00:00 UTC
