### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/DRIVERS/

### ISSUE THREAD

**Issue by werowe** [kubernetes/kubernetes.github.io#2085] opened 2016-12-29 15:41 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

from http://kubernetes.io/docs/getting-started-guides/minikube/#installation
Broken link to http://kubernetes.io/docs/getting-started-guides/minikube/DRIVERS/

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by a-mccarthy** [comment] 2017-01-10 22:23
duplicate of #2182. closing

**Closed by a-mccarthy** 2017-01-10 22:23 UTC
