### ISSUE TITLE
I wish /docs/getting-started-guides/locally I wish this page existed.

### ISSUE THREAD

**Issue by Estebanv** [kubernetes/kubernetes.github.io#988] opened 2016-08-08 13:17 UTC
I wish /docs/getting-started-guides/locally I wish this page existed.

**Comment by yissachar** [comment] 2016-08-08 15:35
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/988

**Comment by jaredbhatti** [comment] 2017-01-10 20:05
Minikube is the way to go now: http://kubernetes.io/docs/getting-started-guides/minikube/

**Closed by jaredbhatti** 2017-01-10 20:05 UTC
