### ISSUE TITLE
Issue with /docs/tutorials/stateful-application/zookeeper/

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/kubernetes.github.io#2154] opened 2017-01-06 21:05 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The config file referenced as http://k8s.io/docs/tutorials/stateful-application/zookeeper.yaml does not exist

**Proposed Solution:**

Host the config file at this location

**Page to Update:**
http://kubernetes.io/docs/tutorials/stateful-application/zookeeper/

Recreating the file as rendered in the tutorial throws errors.

I am investigating but the tutorial and will file additional issues if there is a problem.

**Comment by enisoc** [comment] 2017-01-09 21:12
Attn: @kow3ns

**Comment by steveperry-53** [comment] 2017-01-12 01:29
> The config file referenced as http://k8s.io/docs/tutorials/stateful-application/zookeeper.yaml does not exist

The zookeeper.yaml file does exits, but (best I can tell) it gets mangled during the Jekyll build.

Experiment:
In a browser, enter http://k8s.io/docs/tutorials/stateful-application/gce-volume.yaml.
Everything is fine; you see the YAML file.

Now, in a browser, enter http://k8s.io/docs/tutorials/stateful-application/zookeeper.yaml.
What the heck? You get what looks like the HTML for the kubernetes.io landing page. But if you scroll down, you eventually find the contents of zookeeper.yaml, followed by more HTML:

  <div id="docsContent">
        <p><a href="/editdocs#docs/tutorials/stateful-application/zookeeper.yaml" id="editPageButton">Edit This Page</a></p>      
          <h1></h1>
        apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-config
data:
  ensemble: "zk-0;zk-1;zk-2"
...
        <p><a href=""><img src="https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/docs/tutorials/stateful-application/zookeeper.yaml?pixel" alt="Analytics" /></a>

**Comment by steveperry-53** [comment] 2017-01-12 06:54
I think the problem is thaqt zookeeper.yaml has a triple-dash as its first line. I think Jekyll confuses this for front matter in a markdown file that needs to be built. As soon as the Travis CI issue is fixed, I'll test this idea by merging https://github.com/kubernetes/kubernetes.github.io/pull/2213.

**Comment by steveperry-53** [comment] 2017-01-12 21:44
I'm closing this issue, because the problem the mangle configuration file is fixed. The other problem mentioned in this issue (Recreating the file as rendered in the tutorial throws errors) should get covered as these other two issues are addressed: https://github.com/kubernetes/kubernetes.github.io/issues/2160 and https://github.com/kubernetes/kubernetes.github.io/issues/2159.

**Closed by steveperry-53** 2017-01-12 21:44 UTC
Labels: Actionable, P2

**Comment by emeraldhieu** [comment] 2023-04-24 17:43
I got the same problem. Clicking the link shows the error below. It seems like the file has been moved somewhere.

<img width="817" alt="Screenshot 2023-04-25 at 00 41 58" src="https://user-images.githubusercontent.com/951656/234074733-98cf2ab0-91e9-4bbd-9cb0-6fa9de2f2ab7.png">
