### ISSUE TITLE
I wish /docs/hellonode/ Typo on starting node server

### ISSUE THREAD

**Issue by borg286** [kubernetes/kubernetes.github.io#52] opened 2016-03-05 21:55 UTC
I wish /docs/hellonode/ Typo on starting node server

The docs say to start the server saying

nano server.js

but it should instead be 

node server.js

**Comment by johndmulhausen** [comment] 2016-03-06 06:02
Actually, that is the instruction to launch the nano text editor and edit server.js, entering the information shown in the following snippet. Working as intended, but I'm rewriting this quite soon and will keep this in mind/try to make it more clear. :)

**Comment by pdutourgeerling** [comment] 2016-03-06 17:33
@johndmulhausen isn't the second 'nano server.js' a typo? 
![schermafbeelding 2016-03-06 om 18 31 28](https://cloud.githubusercontent.com/assets/9082394/13555788/c036423c-e3c9-11e5-8029-14fd02ed368b.png)

**Comment by borg286** [comment] 2016-03-06 18:16
Sorry for not being clear, but that is the exact issue I want resolved

**Comment by johndmulhausen** [comment] 2016-03-07 08:27
@borg286 You're totally right! I stopped at the first search result on the page. This is fixed now. Thanks for your patience. :)

**Closed by johndmulhausen** 2016-03-07 08:27 UTC
