### ISSUE TITLE
Deployments should talk a little about :latest

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes.github.io#316] opened 2016-04-04 17:30 UTC
I found two elements missing from `kubernetes.github.io/docs/user-guide/deployments.md` (http://kubernetes.io/docs/user-guide/deployments/):
- Could talk about updating an image tagged `:latest` or with `imagePullPolicy: Always`
- Could talk about ways to deploy linked services like: nginx connecting to uWSGI connecting to PostgreSQL.

**Comment by bgrant0607** [comment] 2016-04-18 21:16
cc @janetkuo

**Comment by bgrant0607** [comment] 2016-04-18 21:22
We should advocate not to use latest:
http://developers.redhat.com/blog/2016/02/24/10-things-to-avoid-in-docker-containers/

And an explanation of why.

I agree multi-tier applications / services belongs somewhere, but not in the deployments doc, other than a reference to it.

Some of that walkthrough content is currently here:
http://kubernetes.io/docs/user-guide/connecting-applications/

**Comment by wernight** [comment] 2016-04-18 22:06
I agree it should be avoided. There are however issues with the fast that Kubernetes doesn't clean up the Registry Container and there is no simpler cleaner for many cloud services.

**Comment by bgrant0607** [comment] 2016-04-19 02:30
Deployment can't be used to trigger a rollout without a spec change, so at best an otherwise innocuous change would have to be made.

**Comment by wernight** [comment] 2016-04-19 07:31
I'd still probably add a pointer to `:latest` for some people. For the rest I'd really put some pointer on to how to clean-up old images in a docker registry because it can quickly take a lot of space.

**Comment by bgrant0607** [comment] 2016-04-19 17:32
Explaining the expected behavior when using :latest seems reasonable.

As for the registry, I agree that's an issue. We run Docker's registry. I don't think it supports direct deletion, but recent versions may support GC of untagged images. If you investigate and find a good solution, we'd be interested to know.

**Comment by wernight** [comment] 2016-04-20 16:02
Docker Registry 2 supports deletion (and it should be soon supported by Google Cloud as well), see also https://stackoverflow.com/questions/36409855. That seems the cleanest API to implement a GC.

**Comment by jaredbhatti** [comment] 2017-01-11 00:15
Closing this issue, since there's been no movement on it over the past 8 months.

**Closed by jaredbhatti** 2017-01-11 00:15 UTC
