### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by minhaz1** [kubernetes/kubernetes.github.io#2712] opened 2017-03-06 07:37 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Getting this error on the interactive tutorial no matter how many times I refresh. Using Safari on Mac OS 10.12
Sorry, we hit a problem with the connection.
Your internet connection may have dropped.

Page: https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/
Please refresh and try again.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment] 2017-03-11 12:03
Thank you for the feedback. We're looking into addressing this now.

**Comment by shufflingB** [comment] 2017-03-14 08:35
fyi ...

Noticed this one myself the other day myself.

The problem is Safari only, both Chrome and Firefox worked for me as temporary workarounds.

**Comment by BenHall** [comment] 2017-03-14 08:45
Thank you for the update. It looks like it's related only to macOS 10.12.3. Safari on older OSX versions it OK.

We're upgrading one of our laptops to debug the issue.

**Comment by BenHall** [comment] 2017-03-15 17:52
The temporary workaround for this is to enable cookies for Katacoda.com. By default it looks like Safari now blocks all cookies.

I'm working on becoming "cookieless"

**Comment by zacharysarah** [comment] 2017-07-14 18:35
@BenHall Thanks for responding here. Can we safely close this issue?

**Comment by BenHall** [comment] 2017-07-15 07:52
Thanks @zacharysarah - Yes, please close as we fixed this issue. Sorry for not updating.

**Closed** 2017-07-15 09:52 UTC
Labels: P2, Tech Review: Open Issues
