### ISSUE TITLE
I wish /docs/getting-started-guides/docker/ existed

### ISSUE THREAD

**Issue by venezia** [kubernetes/kubernetes.github.io#993] opened 2016-08-08 18:06 UTC
Or at least had a 301 to the proper new URL

**Comment by yissachar** [comment] 2016-08-08 22:18
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/984

**Comment by jaredbhatti** [comment] 2017-01-10 19:49
Fixed.

**Closed by jaredbhatti** 2017-01-10 19:49 UTC
