### ISSUE TITLE
Issue with /docs/concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by danieljcosta** [kubernetes/kubernetes.github.io#3975] opened 2017-06-02 10:23 UTC
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Unable to find how is it possible to associate a persitentStorage with the StatefulSet in the documentation.

**Proposed Solution:**
Add an example.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by ahmetb** [comment] 2017-06-02 22:27
Duplicate of #3975.

**Closed by ahmetb** 2017-06-02 22:27 UTC
