### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by np0334** [kubernetes/kubernetes.github.io#3495] opened 2017-04-21 23:17 UTC
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
The start scenario always pops up a message stating the site wants cookies. I have cookies enabled, yet the message wont go away

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment] 2017-04-26 17:18
@np0334 I cannot reproduce. Can you please share a screenshot?

**Comment by ankgupta** [comment] 2017-04-27 01:11
I am getting same error, though it may be just a `funny message` and not browser cookies, but is confusing. 
Safari: 10.1
OS X : 10.12.4

<img width="826" alt="screen shot 2017-04-27 at 6 38 36 am" src="https://cloud.githubusercontent.com/assets/8265493/25463490/4a96a416-2b14-11e7-9e5b-38d0bf2ba58a.png">

**Comment by BenHall** [comment] 2017-05-01 16:46
This happens when 3rd party cookies are not allowed. We're looking at how to support cookieless but taking longer than expected. We'll hopefully have it fixed in the next couple of weeks.

**Comment by ahmetb** [comment] 2017-05-01 17:13
awesome @BenHall thanks!

**Closed** 2017-05-14 18:39 UTC
