### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/update-intro/

### ISSUE THREAD

**Issue by UdayVishwakarma** [kubernetes/kubernetes.github.io#1761] opened 2016-11-22 10:40 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Unable to view other images under "Rolling updates overview" section

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by jaredbhatti** [comment] 2016-11-22 20:25
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/1766

**Closed by jaredbhatti** 2016-11-22 20:25 UTC
