### ISSUE TITLE
I wish /docs/getting-started-guides/docker-multinode/master.sh existed

### ISSUE THREAD

**Issue by ankitkariryaa** [kubernetes/kubernetes.github.io#989] opened 2016-08-08 13:23 UTC
I wish /docs/getting-started-guides/docker-multinode/master.sh existed

**Comment by yissachar** [comment] 2016-08-08 15:34
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/976

**Comment by jaredbhatti** [comment] 2017-01-10 20:07
Fixed.

**Closed by jaredbhatti** 2017-01-10 20:07 UTC
