### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by dpaks** [kubernetes/kubernetes.github.io#2037] opened 2016-12-23 07:32 UTC
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
The _START SCENARIO_  button is overlapped by the Intel footer rendering the button unusable.

**Proposed Solution:**
Adjust the button relative to the other content of the page.

**Page to Update:**
http://kubernetes.io/...

**Comment by a-mccarthy** [comment] 2017-01-10 21:34
duplicate of #2101 and #2050. closing this issue. Please follow issue under #2050

**Closed by a-mccarthy** 2017-01-10 21:34 UTC
