### ISSUE TITLE
Issue with /docs/getting-started-guides/minikube/DRIVERS/

### ISSUE THREAD

**Issue by hickey** [kubernetes/kubernetes.github.io#2071] opened 2016-12-28 18:47 UTC
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Clicking on the "xhyve driver" for information on running Kubernetes on OSX returns a 404 error. 

**Proposed Solution:**
Of course find the proper page and link it properly :-)

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/minikube/

**Comment by hickey** [comment] 2016-12-28 18:51
Sorry, I should clarify, it was not a true 404 page. It was a page that was reporting that the page was not found. The KVM links are trying to go to the same page.

**Comment by a-mccarthy** [comment] 2017-01-10 22:24
duplicate of #2182, closing

**Closed by a-mccarthy** 2017-01-10 22:24 UTC
