### ISSUE TITLE
I wish /docs/getting-started-guides/docker-multinode/master.sh this page existed! i came from http://kubernetes.io/docs/getting-started-guides/docker-multinode/

### ISSUE THREAD

**Issue by apzarabi** [kubernetes/kubernetes.github.io#986] opened 2016-08-07 11:32 UTC
I wish /docs/getting-started-guides/docker-multinode/master.sh this page existed! i came from http://kubernetes.io/docs/getting-started-guides/docker-multinode/

**Comment by yissachar** [comment] 2016-08-08 15:39
Duplicate of https://github.com/kubernetes/kubernetes.github.io/issues/976

**Comment by jaredbhatti** [comment] 2017-01-10 20:08
Fixed.

**Closed by jaredbhatti** 2017-01-10 20:08 UTC
