### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by pueffl** [kubernetes/kubernetes.github.io#5119] opened 2017-08-19 19:20 UTC
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
kubectl proxy doesn't work (never finishes)

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

**Comment by radhikapc** [comment] 2017-08-21 17:30
@BenHall 👋

**Comment by BenHall** [comment] 2017-08-22 08:19
Thank you for the feedback. This is by design on how kubectl proxy works. All the future commands launch in a separate terminal window while Kubectl Proxy is running.

We should make this clearer in the scenario text itself.

**Comment by BenHall** [comment] 2017-08-22 08:19
Related to #5138

**Comment by heckj** [comment] 2017-09-12 21:34
related (original) issue: #1561

**Comment by heckj** [comment] 2017-09-13 19:35
Hi Wolfgang,

This bug matches closely other bugs reported against the use of `kubectl proxy` in the tutorial's hosted at Katacoda. I have a PR pending to resolve, and am closing this bug to focus conversation on the earliest report of this issue: https://github.com/kubernetes/kubernetes.github.io/issues/1561

Please comment at https://github.com/kubernetes/kubernetes.github.io/issues/1561, or subscribe to that bug, to get updates as we work on resolving this.

**Closed by heckj** 2017-09-13 19:35 UTC
Labels: P2, team/katacoda
