### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by gurumaia** [kubernetes/kubernetes.github.io#4940] opened 2017-08-15 12:52 UTC
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
On step 3 of Module 2 of the tutorial, when running `kubectl proxy`, it hangs on `Starting to serve on 127.0.0.1:8001`

**Proposed Solution:**
I have no idea.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

![image](https://user-images.githubusercontent.com/8412398/29316674-3f375ef8-819f-11e7-9d0d-7a57ffe0ebf4.png)

**Comment by gurumaia** [comment] 2017-08-15 13:03
I've just installed minikube and kubectl in my machine to see what happens on my actual linux host. Same thing happens, but then I checked that it is actually listening on port 8001 while it hangs there. So it seems like this is the expected behavior.

Went back to the interactive tutorial and saw that you can open a new tab and it is listening on 8001.

Is this actually expected? Tks

**Comment by zacharysarah** [comment] 2017-08-17 21:06
@BenHall 👋

**Comment by BenHall** [comment] 2017-08-22 08:23
Thank you for the feedback. As you mentioned, this is by design on how kubectl proxy works. We should make this clearer in the scenario text itself as a few people have struggled with this.

Related to #5119 and #5138

**Comment by heckj** [comment] 2017-09-12 21:33
already related (perhaps a duplicate) of #1561

**Comment by heckj** [comment] 2017-09-13 19:36
Thank you Gustavo,

This bug matches closely other bugs reported against the use of `kubectl proxy` in the tutorial's hosted at Katacoda. I have a PR pending to resolve, and am closing this bug to focus conversation on the earliest report of this issue: https://github.com/kubernetes/kubernetes.github.io/issues/1561

Please comment at https://github.com/kubernetes/kubernetes.github.io/issues/1561, or subscribe to that bug, to get updates as we work on resolving this.

**Closed by heckj** 2017-09-13 19:36 UTC
Labels: Needs Tech Review, P2, team/katacoda
